### ISSUE TITLE
Design homepage

### ISSUE THREAD

**Issue by freekmurze** [phpantwerp/phpantwerp.be#1]
Willem, we'll need website with just one page.

These are the things we'd like to show:
```
- Logo
- Intro Tekst (wat is PHP Antwerp)
- Impression Foto's
- Upcoming meetups
- Sponsor logos
- Contact info
- Organisers (Freek, Frederick, Dries)
- Teksten
    - I want to talk
    - I want to host
    - I want to sponsor
```

Here are a few bits of text that we've already written out: https://github.com/phpantwerp/meetups

I'll set up a fresh copy of Laravel 5.4 as soon as that version is tagged.

**Comment by willemvb** [comment]
Is there any existing material regarding corporate identity, logo, colors, fonts? Or total wildcard 🤡?

**Comment by driesvints** [comment]
Logo can be found here: https://github.com/phpantwerp/logo. Thought we decided we wanted to at least have a tad focus on the red and white colors of the Antwerpen logo but besides that you have complete control. Feel free to experiment with whatever you like :)

**Comment by willemvb** [comment]
Let's start with a wireframe. I guess focus should lie on the events / past events first? 

[phpantwerp-wireframes-v1.pdf](https://github.com/phpantwerp/phpantwerp.be/files/773912/phpantwerp-wireframes-v1.pdf)

**Comment by driesvints** [comment]
Hey Willem! Great work, looking forward to the next steps :)

A couple of remarks:

- It's "PHP Antwerp", not "PHPANTWERP"
- Perhaps it's best to show 3 events in advance

Rest of the wireframe looks good 👍

**Comment by willemvb** [comment]
Gonna close this for now ;)
